// Generated by CoffeeScript 1.7.1
(function() {
  app.service('getDepartments', function($http) {
    this.retrieveDepartments = function() {
      return $http.get(dbServer + '/retrieveDepartments').success(function(data, status, headers, config) {
        console.log(data);
        return data;
      }).error(function(data, status, headers, config) {});
    };
  });

  app.controller('DepartmentsCtrl', function($scope, getDepartments) {
    $scope.departments = [];
    getDepartments.retrieveDepartments().then(function(data) {
      return $scope.departments = data.data;
    });
  });

}).call(this);

//# sourceMappingURL=departments.map
