// Generated by CoffeeScript 1.7.1
(function() {
  app.factory('Designations', function() {
    var designations, pick_designation;
    designations = [
      {
        id: "1",
        name: "abc",
        description: "fdhgdth"
      }, {
        id: "2",
        name: "xyz",
        description: "fdhgdth"
      }
    ];
    pick_designation = function(desig) {
      return _.pick(desig, ['name', 'description']);
    };
    return {
      get: function(id) {
        return designations[id];
      },
      index: function() {
        return designations;
      },
      update: function(desig) {
        return _.assign(get(desig.id), pick_designation(desig));
      },
      add: function(desig) {
        return designations.push(_.assign({
          id: designations.length
        }, pick_designation(desig)));
      }
    };
  });

}).call(this);

//# sourceMappingURL=designations.map
