// Generated by CoffeeScript 1.7.1
(function() {
  app.service('loansService', function($http) {
    this.createNewLoan = function(loanType, rateOfInterest, fromDate, todate, description) {
      console.log('new loan added');
      return $http.post(dbServer + '/addLoans', {
        params: {
          loanType: loanType,
          rateOfInterest: rateOfInterest,
          fromDate: fromDate,
          todate: todate,
          description: description
        }
      }).success(function(data, status, headers, config) {
        return data;
      }).error(function(data, status, headers, config) {});
    };
    this.retrieveLoans = function() {
      console.log("loans");
      return $http.get(dbServer + '/retrieveLoans').success(function(data, status, headers, config) {
        console.log(data);
        return data;
      }).error(function(data, status, headers, config) {});
    };
    this.retrieveLoansById = function(loanId) {
      return $http.get(dbServer + '/retrieveLoansById', {
        params: {
          loanId: loanId
        }
      }).success(function(data, status, headers, config) {
        return data;
      }).error(function(data, status, headers, config) {});
    };
    this.editLoans = function(application, loanId) {
      return $http.post(dbServer + 'editLoans', {
        application: application,
        loanId: loanId
      }).success(function(data, status, headers, config) {
        return data;
      }).error(function(data, status, headers, config) {});
    };
  });

  app.controller('AddLoanCtrl', function($scope, $location, loansService) {
    return $scope.createNew = function() {
      loansService.createNewLoan($scope.loan.type, $scope.loan.rateOfInterest, $scope.loan.description).then(function(data) {
        if (data.data.result) {
          return $window.location = '#/adminAddLoans';
        }
      });
      return;
      return $location.path('/adminLoans');
    };
  });

  app.controller('LoansCtrl', function($scope, loansService) {
    $scope.loans = [];
    loansService.retrieveLoans().then(function(data) {
      return $scope.loans = data.data;
    });
  });

}).call(this);

//# sourceMappingURL=manageLoanCtrl.map
