// Generated by CoffeeScript 1.7.1
(function() {
  app.controller('AddShiftCtrl', function($scope, Shifts, $location) {
    return $scope.createShift = function() {
      Shifts.add($scope);
      return $location.path('/admin/showShifts');
    };
  });

  app.factory('Shifts', function() {
    var pick_shifts, shifts;
    shifts = [
      {
        id: "1",
        name: "abc",
        description: "fdhgdth"
      }, {
        id: "2",
        name: "xyz",
        description: "fdhgdth"
      }
    ];
    pick_shifts = function(s) {
      return _.pick(s, ['name', 'description']);
    };
    return {
      get: function(id) {
        return shift[id];
      },
      index: function() {
        return shifts;
      },
      update: function(s) {
        return _.assign(get(s.id), pick_shifts(s));
      },
      add: function(s) {
        return shifts.push(_.assign({
          id: shifts.length
        }, pick_shifts(s)));
      }
    };
  });

}).call(this);

//# sourceMappingURL=manageShiftCtrl.map
