// Generated by CoffeeScript 1.7.1
(function() {
  app.service('designationsService', function($http) {
    this.createNewDesignation = function(desigName, desigDescription, desigDepartment) {
      console.log('new designation added');
      return $http.post(dbServer + '/addDesignation', {
        params: {
          desigName: desigName,
          desigDescription: desigDescription,
          desigDepartment: desigDepartment
        }
      }).success(function(data, status, headers, config) {
        return data;
      }).error(function(data, status, headers, config) {});
    };
    this.retrieveDesignations = function() {
      return $http.get(dbServer + '/retrieveDesignations').success(function(data, status, headers, config) {
        console.log(data);
        return data;
      }).error(function(data, status, headers, config) {});
    };
  });

  app.controller('AddDesignationsCtrl', function($scope, designationsService, $location) {
    return $scope.createNew = function() {
      designationsService.createNewDesignation($scope.designation.name, $scope.designation.description, $scope.designation.department).then(function(data) {
        if (data.data.result) {
          return $window.location = '#/adminDesignations';
        }
      });
    };
  });

  app.controller('DesignationsCtrl', function($scope, designationsService, ngTableParams) {
    $scope.designations = [];
    designationsService.retrieveDesignations().then(function(data) {
      $scope.designations = data.data;
      console.log('hello3' + data);
      console.log('hello5' + data.length);
      return console.log('hello' + $scope.designations.length);
    });
    $scope.manageDesignation = new ngTableParams({
      page: 1,
      count: 10
    }, {
      total: $scope.designations.length
    }, console.log('hello2' + $scope.designations.length), console.log('helloworld'), {
      getData: function($defer, params) {
        var orderedData;
        orderedData = (params.sorting() ? $filter("orderBy")(filteredData, params.orderBy()) : $scope.designations);
        params.total(orderedData.length);
        $defer.resolve(orderedData.slice((params.page() - 1) * params.count(), params.page() * params.count()));
      }
    });
  });

}).call(this);

//# sourceMappingURL=manageDesignationCtrl.map
