// Generated by CoffeeScript 1.6.3
app.service('AbsentApply', function($http) {
  this.retrieveApplications = function() {
    return $http.get(dbServer + '/retrieveAbsent', {
      params: {
        user: $.cookie("user")
      }
    }).success(function(data, status, headers, config) {
      return data;
    }).error(function(data, status, headers, config) {});
  };
  this.retrieveAbsentTypes = function() {
    return $http.get(dbServer + '/retrieveAbsentTypes', {
      params: {
        user: $.cookie("user")
      }
    }).success(function(data, status, headers, config) {
      return data;
    }).error(function(data, status, headers, config) {});
  };
  this.newAbsentApplication = function(application) {
    return $http.post(dbServer + '/newAbsentApplication', {
      params: {
        application: application,
        user: $.cookie("user")
      }
    }).success(function(data, status, headers, config) {
      return data;
    }).error(function(data, status, headers, config) {});
  };
});

app.controller('AbsentApplyCtrl', function($scope, $stateParams, AbsentApply, $filter, ngTableParams) {
  var absentList;
  absentList = function() {
    return AbsentApply.retrieveApplications().then(function(data) {
      data = data.data;
      $scope.dataTableAbsentApply = new ngTableParams({
        page: 1,
        count: 10
      }, {
        total: data.length,
        getData: function($defer, params) {
          var filteredData, orderedData;
          filteredData = (params.filter() ? $filter("filter")(data, params.filter()) : data);
          orderedData = (params.sorting() ? $filter("orderBy")(filteredData, params.orderBy()) : data);
          params.total(orderedData.length);
          $defer.resolve(orderedData.slice((params.page() - 1) * params.count(), params.page() * params.count()));
        }
      });
    });
  };
  absentList();
  AbsentApply.retrieveAbsentTypes().then(function(data) {
    return $scope.absentType = data.data;
  });
  $scope.submit = function() {
    return AbsentApply.newAbsentApplication($scope.application).then(function(data) {
      if (data.data.result) {
        $scope.absent = true;
        absentList();
        return $scope.application = {
          fromDate: "",
          toDate: "",
          absentType: "",
          reason: ""
        };
      }
    });
  };
});

/*
//@ sourceMappingURL=absentApply.map
*/
