// Generated by CoffeeScript 1.7.1
app.service('LeaveApply', function($http) {
  this.retrieveApplications = function() {
    return $http.get(dbServer + '/retrieveLeave', {
      params: {
        user: $.cookie("user")
      }
    }).success(function(data, status, headers, config) {
      return data;
    }).error(function(data, status, headers, config) {});
  };
  this.retrieveLeaveTypes = function() {
    return $http.get(dbServer + '/retrieveLeaveTypes', {
      params: {
        user: $.cookie("user")
      }
    }).success(function(data, status, headers, config) {
      return data;
    }).error(function(data, status, headers, config) {});
  };
  this.newLeaveApplication = function(application) {
    return $http.post(dbServer + '/newLeaveApplication', {
      params: {
        application: application,
        user: $.cookie("user")
      }
    }).success(function(data, status, headers, config) {
      return data;
    }).error(function(data, status, headers, config) {});
  };
});

app.controller('LeaveApplyCtrl', function($scope, $stateParams, LeaveApply, $filter, ngTableParams) {
  var leaveList;
  leaveList = function() {
    return LeaveApply.retrieveApplications().then(function(data) {
      data = data.data;
      $scope.dataTableLeaveApply = new ngTableParams({
        page: 1,
        count: 10
      }, {
        total: data.length,
        getData: function($defer, params) {
          var filteredData, orderedData;
          filteredData = (params.filter() ? $filter("filter")(data, params.filter()) : data);
          orderedData = (params.sorting() ? $filter("orderBy")(filteredData, params.orderBy()) : data);
          params.total(orderedData.length);
          $defer.resolve(orderedData.slice((params.page() - 1) * params.count(), params.page() * params.count()));
        }
      });
    });
  };
  leaveList();
  LeaveApply.retrieveLeaveTypes().then(function(data) {
    return $scope.leaveType = data.data;
  });
  $scope.submit = function() {
    return LeaveApply.newLeaveApplication($scope.application).then(function(data) {
      if (data.data.result) {
        $scope.leave = true;
        leaveList();
        return $scope.application = {
          fromDate: "",
          toDate: "",
          leaveType: "",
          reason: ""
        };
      }
    });
  };
});

//# sourceMappingURL=leaveApply.map
