// Generated by CoffeeScript 1.7.1
(function() {
  app.service('OvertimeApply', function($http) {
    this.retrieveApplications = function() {
      return $http.get(dbServer + '/retrieveOvertime', {
        params: {
          user: $.cookie("user")
        }
      }).success(function(data, status, headers, config) {
        return data;
      }).error(function(data, status, headers, config) {});
    };
    this.newOvetimeApplication = function(application) {
      return $http.post(dbServer + '/newOvertimeApplication', {
        params: {
          application: application,
          user: $.cookie("user")
        }
      }).success(function(data, status, headers, config) {
        return data;
      }).error(function(data, status, headers, config) {});
    };
  });

  app.controller('OvertimeApplyCtrl', function($scope, $stateParams, OvertimeApply, $filter, ngTableParams) {
    var overtimeList;
    overtimeList = function() {
      return OvertimeApply.retrieveApplications().then(function(data) {
        data = data.data;
        $scope.dataTableOvertimeApply = new ngTableParams({
          page: 1,
          count: 10
        }, {
          total: data.length,
          getData: function($defer, params) {
            var filteredData, orderedData;
            filteredData = (params.filter() ? $filter("filter")(data, params.filter()) : data);
            orderedData = (params.sorting() ? $filter("orderBy")(filteredData, params.orderBy()) : data);
            params.total(orderedData.length);
            $defer.resolve(orderedData.slice((params.page() - 1) * params.count(), params.page() * params.count()));
          }
        });
      });
    };
    overtimeList();
    $scope.submit = function() {
      return OvertimeApply.newOvertimeApplication($scope.application).then(function(data) {
        if (data.data.result) {
          $scope.leave = true;
          overtimeList();
          return $scope.application = {
            date: "",
            from: "",
            to: "",
            reason: ""
          };
        }
      });
    };
  });

}).call(this);

//# sourceMappingURL=overtimeApply.map
