// Generated by CoffeeScript 1.7.1
(function() {
  app.controller('addEmpCtrl', function($scope, $http, $window) {
    console.log('addEmpCtrl');
    return $scope.submit = function() {
      return console.log('submit');
    };
  });

}).call(this);

//# sourceMappingURL=addEmp.map
