// Generated by CoffeeScript 1.7.1
(function() {
  app.service('AttendanceService', function($http) {
    this.retrieveEmployeesAttendance = function(user, date) {
      return $http.get(dbServer + '/retrieveEmployeesAttendance', user).success(function(data, status, headers, config) {
        return data.result;
      }).error(function(data, status, headers, config) {});
    };
    return;
  });

  app.controller('ManualAttendanceCtrl', function($scope, AttendanceService) {
    AttendanceService.retrieveEmployeesAttendance($scope.user).then(function(data) {});
    return $scope.submit = function() {};
  });

}).call(this);

//# sourceMappingURL=manualAttendance.map
