// Generated by CoffeeScript 1.7.1
(function() {
  app.service('Attandance', function($http) {});

  app.controller('ManualAttandanceCtrl', function($scope, Attandance) {});

}).call(this);

//# sourceMappingURL=manualAttandance.map
