// Generated by CoffeeScript 1.7.1
(function() {
  app.service('Reimbursement', function($http) {});

  app.controller('ReimbursementCtrl', function($scope, Leave) {});

  app.controller('ReimbursementEmpCtrl', function($scope, Leave) {});

}).call(this);

//# sourceMappingURL=reimbursement.map
