// Generated by CoffeeScript 1.6.3
app.service('headerService', function($http) {
  this.retrievePrivileges = function(user) {
    return $http.get(dbServer + '/retrievePrivileges', {
      params: {
        user: user
      }
    }).success(function(data, status, headers, config) {
      return data;
    }).error(function(data, status, headers, config) {});
  };
});

app.controller('HeaderCtrl', function($scope, $window, headerService) {
  return headerService.retrievePrivileges($.cookie("user")).then(function(data) {
    console.log(data);
    $scope.user = data.data;
    $scope.user.username = $.cookie("userName");
    return console.log($scope.user);
  });
});

/*
//@ sourceMappingURL=header.map
*/
