// Generated by CoffeeScript 1.6.3
app.service('userService', function($http) {
  this.validate = function(user) {
    return $http.post(dbServer + '/login', user).success(function(data, status, headers, config) {
      return data.result;
    }).error(function(data, status, headers, config) {});
  };
});

app.controller('LoginCtrl', function($scope, $window, userService) {
  $scope.user = {};
  $scope.user.rememberme = false;
  $scope.submit = function() {
    userService.validate($scope.user).then(function(data) {
      if (data.data.result === true) {
        if ($scope.user.rememberme) {
          $.cookie("user", data.data.user, {
            expires: 1
          });
          $.cookie("userName", data.data.userName, {
            expires: 1
          });
          $.cookie("manager", data.data.manager, {
            expires: 1
          });
        } else {
          $.cookie("user", data.data.user);
          $.cookie("userName", data.data.userName);
          $.cookie("manager", data.data.manager);
        }
        $window.location = '#/dashboard';
      } else if (data.data.result === false) {
        $scope.passwordError = false;
        $scope.error = true;
        $('#username').val('');
        $('#username').focus();
        $('#password').val('');
      } else if (data.data.result === "passwordError") {
        $scope.error = false;
        $scope.passwordError = true;
        $('#password').val('');
        $('#password').focus();
      }
    });
  };
});

/*
//@ sourceMappingURL=index.map
*/
